quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.log.category."io.github.ravocode.avoonce".level=DEBUG

quarkus.index-dependency.avoonce.group-id=io.github.ravocode.avoonce
quarkus.index-dependency.avoonce.artifact-id=idempotency-jaxrs
